export { default as Landing } from './landing'
export { default as StandardCircuit } from './standardcircuit'
export { default as HighestRoad } from './highestroad'
export { default as Cancellation } from './cancellation'
export { default as Terms } from './terms'
export { default as About } from './about'
